name: First Workflow
on: workflow_dispatch
jobs:
  first-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "This is my first workflow"
      - name: Print Bye
        run: echo "See you in 2nd workflow"