name: Test Project
on: 
  push:
    branches: 
      - main
  workflow_dispatch: 
     
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code from Repository
        uses: actions/checkout@v3
        with:
          repository: msdn2023/msdn101
          path: second-action-react-demo
      - name: Install NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
